X-lab2017/oss101

Assignments/Assignment-typo.md

add: Assignment-typo.md 作业资源

---

Assignments/Assignment-typo.md

fix https://github.com/X-lab2017/oss101/issues/71
fix skip letter typo 'dpends' line 19 to 'depends'
fix extra letter typo 'annhoying' line 195 to 'annoying'
fix skip letter 'imge' line 311 to 'image'
fix wrong letter typo 'Than' line 409 to 'Then'
team: 51255903026 51255903022

typo: 'dpends' at 19, 'Than' at 409, 'annoying' at 195, 'imge' at 311

---

Assignments/Assignment-typo.md

fix #71 
- fix:wrong letter at line 25 reputation
- fix extra space typo 'simi lar' at line 173 to 'similar'
- fix wrong letter at 549 'sare' to 'sure'
team ：51255903033,51255903031,51255903092，51255903073

typo: at line 549, 173, 25

---

Assignments/Assignment-typo.md

fix #71 
- fix wrong letter typo `thair` at line 377 to `their`
- fix extra letter typo  `readding` at line 379 to `reading`
- fix skip letter typo `attmpts` at line 357 to `attempts`
team: @Freejww 51255903057   @lxr599 51255903012   @tiertie 51255903104

typo:thair at line 377, attmpts at line 357, reaading at line 379 

---

Assignments/Assignment-typo.md

fix #71 
fix Skip spaces typo 'daysor' at line 149 to 'days or'
fix wrong letter typo 'clams' at line 435 to 'claims'
fix wrong letter typo 'eaier' at line 441 to 'easier'
51255903089 51255903085 51255903045

typo: at line 149, 435,441

---

Assignments/Assignment-typo.md

fix #71
- fix skip space typo `yourbug`at line 257 to `your bug`
- fix extra space typo `whe ther` at line 447 to `whether`
- fix extra space typo `ques tions` at line 117 to `questions`
team: 51255903023,51255903061,51255903109

typo: 'yourbug' at line 257, 'whe ther' at line 447, 'ques tions' at line 117 

---

Assignments/Assignment-typo.md

fix [](https://github.com/X-lab2017/oss101/issues/71)
fix skip letter typo 'tld' at line 437 to 'told' 
fix skip letter typo 'qustion' at line 411 to 'question' 
fix skip letter typo 'imgination' at line 443 to 'imagination'
team: 51255903095 51255903100 51255903097 51255903074

typo: 'tld' at line 437,  'qustion' at line 411, 'imgination' at line 443

---

Assignments/Assignment-typo.md

fix #71 
fix wrong letter typo "tht" in line 359 to "that"
fix extra space typo "humiliationfor" at line 547 to "humiliation for"
fix wrong letter typo "then" in line 563 to "than"
fix wrong letter typo"queraent" at line 559 to "querent"(这个和别的组重复了)
team: 51255903021 51255903083

typo: 'tht' at line 359, 'humiliationfor' at line 547, 'then' at line 563.

---

Assignments/Assignment-typo.md

fix #71 
fix skip space typo:'bevery' at line 387 to 'be very'
fix extra space typo:'relia bly' at line 361 to 'reliably'
fix Wrong letter typo:'bat' at line 191 to 'bet'
team: 51255903096, 51255903093, 51255903106, 51255903036

typo: bevery at line 387, reli ably at line 361, bat at line 191

---

Assignments/Assignment-typo.md

We have made the modifications to the https://github.com/X-lab2017/oss101/pull/91 according to your request
Fix https://github.com/X-lab2017/oss101/issues/71
Team members: 52265903002, 52265903008
In summary, 
- fix wrong letter typo `rezplying` at line 555 to `replying`
- fix wrong letter typo `sare` at line 549 to `sure`
- fix wrong letter typo `feshion` at line 439 to `fashion`

typo: at line 439, 549, 555

---

Assignments/Assignment-typo.md

fix #71 
1. fix extra space typo `espe cially` at line 249 to `especially`
2. fix extra letter typo `coloor` at line 229 to `color`
3. fix wrong letter typo `bat` at line 191 to `bet`
4. fix extra letter typo `answaers` at line 321 to `answers`

typo: at line 249, 229, 191 ,321

---

Assignments/Assignment-typo.md

fix #71 
- fix extra space typo 'sep arate' at line 275 to 'separate'
- fix extra space typo ques tions line 117 to questions
- fix skip spaces typo asyou line 225 to as you
51255903015 51255903014 51255903062  52275903004

typo:at line 275,117,225

---

Assignments/Assignment-typo.md

fix #71 
1. fix extra letter typo `annhoying` at line 195 to `annoying`
2. fix wrong letter typo `respendent` at line 405 to `respondent`
3. fix extra letter typo `clarrification` at line 409 to `clarification`
team: 51255903041 51255903043 51255903044

typo: `annhoying` at line 195, `respendent` at line 405, `clarrification` at line 409

---

Assignments/Assignment-typo-for-cloud-computing.md

fixes #143 
- Fix wrong letter typo `paseed` at line 213@Breesiu
- Fix wrong letter typo `Thse` at line 325@LiXinyuan1015
- Fix wrong letter typo `laok` at line 155@Bruce-Jay
team: 10205501452 10205501425 10205501411

typo: `Thse` at line 325, `paseed` at line 213, `laok` at line 131

---

Assignments/Assignment-typo-for-cloud-computing.md

* fix wrong letter typo demoestrated at line 523 to demonstrated @foliet
* fix wrong letter typo tre at line 551 to the @foliet
* fix wrong letter typo illuetrate at line 493 to illustrate @foliet
team: 10205501422为一人两账号独立完成

typo: `tre` at line 551,`illuetrate` at line 493,`demoestrated` at line 523

---

Assignments/Assignment-typo-for-cloud-computing.md

- fix extra space typo be ing at line 257 to being @Silhouette0
- fix skip letter typo havewritten at line 537 to have written @melodrama04
- fix wrong letter typo demoestrated at line 523 to demonstrated @toodeoo
team: 10205501408 10205501416 10205501439 10205501458

typo:`bei ng` at line 257, `havewritten` at line 537, `demoestrated` at line 523

---

Assignments/Assignment-typo.md

fix #71
-fix extra letter typo reaputation at line 25 to reputation
team:我不知道学号填什么

typo: `reaputation` at line 25 

---

Assignments/Assignment-typo-for-cloud-computing.md

+ fix Extra letter typo 'newsbie' at line125 to 'newbie' @ZhangChunXian
+ fix Skip letter typo 'conslting' at line 279 to 'consulting' @ZhangChunXian
+ fix Skip letter typo 'rdely' at line 271 to 'rudely' @ZhangChunXian
team: 10205501451

typo: `newsbie` at line 125, `conslting` at line 279, `rdely` at line 271

---

Assignments/Assignment-typo-for-cloud-computing.md

- fix wrong letter typo `Unqx` at line 97 to `Unix` @BhJia
- fix wrong letter typo `menu-bastd` at line 231 to `menu-based` @Daserxqc
- fix extra space typo `co de` at line 331 to `code` @sunny-max-creater
team: 10205501423  10205501413  10205501455

typo: `Unqx` at line 97 , `menu-bastd` at line 231, `co de` at line 331

---

.github/workflows/add-reaction.yaml

Revert "ci: add `tennnx` to reaction list"

---

.github/workflows/add-reaction.yaml

ci: add qqliang to reaction list~

ci: add `qqliang` to reaction list~

---

Assignments/Assignment-typo-for-cloud-computing.md

修正第一次提交时的格式问题
修正第二次提交时使用了main
typo: thde at line 155, "bo und" at line 181, 'axre' at line 191
Team 10205501415 10205501436 10205501438 10205501440

typo: thde at line 155, "bo und" at line 181, 'axre' at line 191

---

.github/workflows/add-reaction.yaml

ci: add `yz2022` to reaction list

ci: add `yz2022` to reaction list

---

Assignments/Assignment-typo-for-cloud-computing.md
Assignments/Assignment-typo.md

Fix skip letter typo 'archve-searching' at line 401 and verb tense typo 'irritates' at line 95.

Fix skip letter typo 'archve-searching' at line 401 and verb tense typo 'irritates' at line 95.

---

Assignments/Assignment-typo.md

typo: friend at line 89. inyour at line 151. followup at line 377.

typo: friend at line 89. inyour at line 151. followup at line 377.

---

Assignments/Assignment-typo-for-cloud-computing.md

fixes #143
- fix extra space typo `yo ur` at line 339 to `your`  @0205501435 xxxxxiwu(also names StarsFunctions)
- fix skip letter typo `thbir` at line 443  to `their` @10195501401 Ice-cream1024
- fix extra space typo(s)  `Ysou` at line 227 to `You`  @10205501435 xxxxxiwu(also names StarsFunctions)
team: 10205501435 10195501401

typo: `Ysou` at line 227, `thbir` at line 443, `yo ur` at line 339 

---

Assignments/Assignment-typo-for-cloud-computing.md

- fix skip space typo `organizeyour` at line 171 to `organize your`   @ecnu-yzj
- fix extra space typo `pro gram` at line 359 to `program`                @ecnu-yzj
- fix skip space typo `whichsolution`at line 385 to `which solution`  @ecnu-yzj
team:10205501410

 typo: 'organizeyou' at line 171 ',pro gram'at line 359, 'whichsolution' at line 385

---

.github/workflows/add-reaction.yaml

ci: add `JinkaiXu` to reaction list

ci: add `JinkaiXu` to reaction list

---

.github/workflows/add-reaction.yaml

ci: add `qkgoalkeeper` to reaction list
